name: Core2Web
run-name: Java Code Run
on: 
  push: 
    paths: 
        - '**.java'
jobs:
  Run-Java-Code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: sudo apt update
      - run: sudo apt install openjdk-17-jdk
      run: |  
    echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}  
          - name: Setup Environment (Push)  
        if: ${{ github.event_name == 'push' }}  
        shell: bash  
  run: |  
  echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
      - run: echo ${{GITHUB_SHA}}
   