name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  Run_Java_Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    
      with:
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        fetch-depth: 2
     #   ref: ${{ github.event.pull_request.head.sha }}
    
    ######- run: echo "{{$GITHUB_SHA}}"
    ######- run: java -version
    #- run: FILE_PAT="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
    #-  run: |
          #git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
   #- run: echo "FILE_PAT=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
    #-echo "::workflow-git diff-tree --no-commit-id --name-only -r ${{ github.sha }}::{command value}"


   # - run: echo "FILE_PAT=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_ENV
    #- run: echo "$GITHUB_ENV"
    #- run: echo "${{env.FILE_PAT}}"
    #- run: echo $FILE_PAT
    #- run: echo "${{ github.event.pull_request.head.sha }}"
    - name: Retrieve version
      run: |
       echo "::git diff-tree --no-commit-id --name-only -r ${{ github.sha }}::{name}"
       echo "$NAME"
       git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
       echo "::set-output name=coverage::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
      id: version
   # - name: Create Release
     # id: create_release
      #uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      #with:
       # tag_name: ${{ env.TAG_NAME }}

    - run: echo "${{ steps.version.outputs.coverage }}"
    - run: ${{steps.version.outputs.name}}
    - run: echo "${{steps.version.outputs.name}}" 
    
    - name: Set the value
      id: step_one
      run: |
       echo "action_state=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }}`" >> "$GITHUB_ENV"
    - name: Use the value
      id: step_two
      run: |
         echo "${{ env.action_state }}" # This will output 'yellow'
   
    action "git command" {
      uses = "srt32/git-actions@v0.0.3"
      args = "git status"
      }
      
    #- name: 'Create delta packages for new, modified or deleted metadata'
    #  run: | 
     #     mkdir changed-sources
      #    echo "DIFF=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_ENV
     
     
  #  - name: NEW STEP
   #   run: |
    #   echo "${{ env.DIFF }}"
     #  sfdx sgd:source:delta --to "HEAD" --from ${{ env.DIFF }} --output changed-sources/ --generate-delta --source force-app/