name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  Run_Java_Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
    
      with:
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        fetch-depth: 2
        ref: ${{ github.event.pull_request.head.sha }}
    
   # - run: java ${{$GITHUB_SHA}}
    - run: java -version
    - run: echo "${{ github.event.pull_request.head.sha }}"
    
   - id: files
      - uses: jitterbit/get-changed-files@v1
    - run: |
    for changed_file in ${{ steps.files.outputs.all }}; do
      echo "Do something with this ${changed_file}."
    done