name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  check-Java-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: apt install openjdk-17-jdk
      - run: java -version