name: Core2Web
run-name: Java Code Run
on: 
  push:
jobs:
  GET_CHANGED_FILENAME:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    
      with:
        fetch-depth: 0
        
   
    - run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
    
    - name: Retrieve version
      run: |
             echo "::set-output name=coverage::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
  

    - run: echo "${{ steps.version.outputs.coverage }}"
   # - run: ${{steps.version.outputs.name}}
   # - run: echo "${{steps.version.outputs.name}}" 
    
    #- name: Set the value
    #  id: step_one
    #  run: |
    #   echo "action_state=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }}`" >> "$GITHUB_ENV"
    #- name: Use the value
    #  id: step_two
    #  run: |
    #     echo "${{ env.action_state }}" # This will output 'yellow'
   
   
    #- name: 'Create delta packages for new, modified or deleted metadata'
    #  run: | 
              echo "DIFF=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_ENV
     
     
    #- name: NEW STEP
    #  run: |
    #   echo "${{ env.DIFF }}"
       
    - name: Run Java Code
      uses: actions/setup-java@v3
      with:
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Run Java Command
      run: |
       java ${{ steps.version.outputs.coverage }}
     
  