name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  Run_Java_Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
    - uses: jitterbit/get-changed-files@v1
    
      with:
      # Format of the steps output context.
    # Can be 'space-delimited', 'csv', or 'json'.
    # Default: 'space-delimited'
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        fetch-depth: 2
        format: ''
        ref: ${{ github.event.pull_request.head.sha }}
    #- run: sudo apt update
    #- run: sudo apt install openjdk-8-jdk
   # - run: java ${{$GITHUB_SHA}}
    - run: java -version
    - run: echo "${{ github.event.pull_request.head.sha }}"