name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  Run_Java_Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
    
      with:
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        fetch-depth: 2
     #   ref: ${{ github.event.pull_request.head.sha }}
    
    ######- run: echo "{{$GITHUB_SHA}}"
    ######- run: java -version
    #- run: FILE_PAT="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
    -  run: `git diff-tree --no-commit-id --name-only -r ${{ github.sha }})`
   #- run: echo "FILE_PAT=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
    #-echo "::workflow-git diff-tree --no-commit-id --name-only -r ${{ github.sha }}::{command value}"


   # - run: echo "FILE_PAT=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_ENV
    #- run: echo "$GITHUB_ENV"
    #- run: echo "${{env.FILE_PAT}}"
    #- run: echo $FILE_PAT
    #- run: echo "${{ github.event.pull_request.head.sha }}"
    
       

      