name: Core2Web
run-name: Java Code Run
on: 
  push: 
    paths: 
        - '**.java'
        
    shell: bash  
jobs:
  Run-Java-Code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
                        
       
      - run: echo "$GITHUB_SHA"
   