name: Core2Web
run-name: Java Code Run
on: 
  push: 
    paths: 
        - '**.java'
jobs:
  Run-Java-Code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: java ${GITHUB_SHA}
   