name: Core2Web
run-name: Java Code Run
on: [push]
jobs:
  Run Java Code:
    runs-on: ubuntu-latest
   steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    repository: /PreranaS24/Core2Web
    distribution: 'temurin' # See 'Supported distributions' for available options
    java-version: '1.8'
- run: java -version