name: Core2Web
run-name: Java Code Run
on: 
  push:
jobs:
  GET_CHANGED_FILENAME:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    
      with:
        fetch-depth: 0
        
   
    - run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
    
    - name: Retrieve version
      run: |
             echo "::set-output name=coverage::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
        
    - run: echo "${{ steps.version.outputs.coverage }}"
   
       
    - name: Run Java Code
      uses: actions/setup-java@v3
      with:
        distribution:  'oracle' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Run Java Command
      run: |
       java ${{ steps.version.outputs.coverage }}
     
  